site_name: "Landing page of hpcuantwerpen (CalcUA service) on GitHub"
site_url: https://hpcuantwerpen.github.io/
site_dir: site
site_description: >-
  GitHub landing page of hpcuantwerpen (CalcUA service)

theme:
  name: material
  # We'll customise the team (basically a simpler footer)
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - header.autohide
    - toc.follow
  palette:
    - primary: black

#hide:
#  - toc

nav:
  - Links: index.md

plugins:
  # show revision date at bottom of each page
  - git-revision-date-localized

markdown_extensions:
  - meta
  # Nicer tables
  - tables
  # notes, warnings, hints, ...
  - admonition
  # code blocks with syntax highlighting, graphs
  - pymdownx.superfences:
        custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # clickable details
  - pymdownx.details
  # tabbed contents
  - pymdownx.tabbed
  - toc:
      permalink: false
      toc_depth: 3

extra_css:
  - stylesheets/extra.css

extra:
  # add links in bottom right
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hpcuantwerpen
      name: HPC-UAntwerpen on GitHub
